server:
  port: 18695

spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:18695/eureka/ # 此处改为第二个eureka-server地址
  server:
      waitTimeInMsWhenSyncEmpty: 0
      enableSelfPreservation: false