server:
  port: 18693

spring:
  application:
    name: eureka-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18694/eureka/
#      defaultZone: http://localhost:18694/eureka/,http://localhost:18695/eureka/